// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyAspire.Database.Migrations
{
    [DbContext(typeof(MyAspireDbContext))]
    partial class MyAspireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phase 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phase 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phase 3"
                        });
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = 8,
                            RoundId = 1,
                            Text = "What is 5 + 3?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = 8,
                            RoundId = 1,
                            Text = "What is 12 - 4?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = 42,
                            RoundId = 1,
                            Text = "What is 7 * 6?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = 9,
                            RoundId = 1,
                            Text = "What is 81 / 9?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = 8,
                            RoundId = 1,
                            Text = "What is the square root of 64?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = 3,
                            RoundId = 1,
                            Text = "What is 15 % 4?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = 8,
                            RoundId = 1,
                            Text = "What is 2^3?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = 55,
                            RoundId = 1,
                            Text = "What is 100 - 45?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = 41,
                            RoundId = 1,
                            Text = "What is 14 + 27?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = 81,
                            RoundId = 1,
                            Text = "What is 9 * 9?"
                        },
                        new
                        {
                            Id = 11,
                            Answer = 42,
                            RoundId = 2,
                            Text = "What is 25 + 17?"
                        },
                        new
                        {
                            Id = 12,
                            Answer = 12,
                            RoundId = 2,
                            Text = "What is 144 / 12?"
                        },
                        new
                        {
                            Id = 13,
                            Answer = 54,
                            RoundId = 2,
                            Text = "What is 18 * 3?"
                        },
                        new
                        {
                            Id = 14,
                            Answer = 66,
                            RoundId = 2,
                            Text = "What is 99 - 33?"
                        },
                        new
                        {
                            Id = 15,
                            Answer = 121,
                            RoundId = 2,
                            Text = "What is 11^2?"
                        },
                        new
                        {
                            Id = 16,
                            Answer = 3,
                            RoundId = 2,
                            Text = "What is the cube root of 27?"
                        },
                        new
                        {
                            Id = 17,
                            Answer = 56,
                            RoundId = 2,
                            Text = "What is 7 * 8?"
                        },
                        new
                        {
                            Id = 18,
                            Answer = 1,
                            RoundId = 2,
                            Text = "What is 50 % 7?"
                        },
                        new
                        {
                            Id = 19,
                            Answer = 8,
                            RoundId = 2,
                            Text = "What is 64 / 8?"
                        },
                        new
                        {
                            Id = 20,
                            Answer = 100,
                            RoundId = 2,
                            Text = "What is 123 - 23?"
                        },
                        new
                        {
                            Id = 21,
                            Answer = 81,
                            RoundId = 3,
                            Text = "What is 3^4?"
                        },
                        new
                        {
                            Id = 22,
                            Answer = 16,
                            RoundId = 3,
                            Text = "What is 256 / 16?"
                        },
                        new
                        {
                            Id = 23,
                            Answer = 90,
                            RoundId = 3,
                            Text = "What is 45 * 2?"
                        },
                        new
                        {
                            Id = 24,
                            Answer = 125,
                            RoundId = 3,
                            Text = "What is 200 - 75?"
                        },
                        new
                        {
                            Id = 25,
                            Answer = 11,
                            RoundId = 3,
                            Text = "What is the square root of 121?"
                        },
                        new
                        {
                            Id = 26,
                            Answer = 1000,
                            RoundId = 3,
                            Text = "What is 10^3?"
                        },
                        new
                        {
                            Id = 27,
                            Answer = 4,
                            RoundId = 3,
                            Text = "What is 81 % 7?"
                        },
                        new
                        {
                            Id = 28,
                            Answer = 225,
                            RoundId = 3,
                            Text = "What is 15 * 15?"
                        },
                        new
                        {
                            Id = 29,
                            Answer = 20,
                            RoundId = 3,
                            Text = "What is 500 / 25?"
                        },
                        new
                        {
                            Id = 30,
                            Answer = 200,
                            RoundId = 3,
                            Text = "What is 99 + 101?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
